set shell := ["nu", "-c"]

fatt-c:
	echo "Building Plang with JIT"
	./pypy/rpython/bin/rpython fatt.py

fatt-c-jit:
	echo "Building Plang with JIT"
	./pypy/rpython/bin/rpython -Ojit fatt.py

format:
	black fatt*.py

setup-dev:
	rm -rf rply appdirs.py
	git clone https://github.com/pypy/pypy.git
	wget https://raw.githubusercontent.com/ActiveState/appdirs/48357882e5c095003e10f8351b405bf54e41424f/appdirs.py
	git clone https://github.com/alex/rply.git rplyrepo
	mv rplyrepo/rply .
	rm -rf rplyrepo

test-fatt-c: (test "../cli.tests" "fatt-c")

test FILE BIN:
    open {{FILE}} | lines | where {|line| ($line | str length) > 0 and not ($line | str starts-with "#") } | each {|$line| ./{{BIN}} $"($line)"; print ""}
