
test: build
    deno test -A --v8-flags="--experimental-wasm-jspi" fatt.test.js

build:
    wasm-tools validate -g --features=gc,function-references fatt.wat
    wasm-tools parse fatt.wat -o fatt.wasm
    wasm-tools print fatt.wasm

opt:
    wasm-opt -Os --enable-multivalue --enable-gc --enable-reference-types fatt.wasm -o fatto.wasm

print-opt:
    wasm-tools print fatto.wasm
